// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0MsPIf4PjUnZkEV7gk41VIxYPosats0k',
    appId: '1:849122357390:web:afab1744de9967634759df',
    messagingSenderId: '849122357390',
    projectId: 'flutter-firebase-1b945',
    authDomain: 'flutter-firebase-1b945.firebaseapp.com',
    storageBucket: 'flutter-firebase-1b945.firebasestorage.app',
    measurementId: 'G-D4P4TJ0YR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU7n2i4KBuXoajAXM1cjXoVpWt7fsKHdE',
    appId: '1:849122357390:android:cb03a930840ed7934759df',
    messagingSenderId: '849122357390',
    projectId: 'flutter-firebase-1b945',
    storageBucket: 'flutter-firebase-1b945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCToe4t-rRN8LQF_6iqzgNMZVP7bMEV48o',
    appId: '1:849122357390:ios:22c9750c934aa1014759df',
    messagingSenderId: '849122357390',
    projectId: 'flutter-firebase-1b945',
    storageBucket: 'flutter-firebase-1b945.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCToe4t-rRN8LQF_6iqzgNMZVP7bMEV48o',
    appId: '1:849122357390:ios:22c9750c934aa1014759df',
    messagingSenderId: '849122357390',
    projectId: 'flutter-firebase-1b945',
    storageBucket: 'flutter-firebase-1b945.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0MsPIf4PjUnZkEV7gk41VIxYPosats0k',
    appId: '1:849122357390:web:0d52b4b39d0d5c2e4759df',
    messagingSenderId: '849122357390',
    projectId: 'flutter-firebase-1b945',
    authDomain: 'flutter-firebase-1b945.firebaseapp.com',
    storageBucket: 'flutter-firebase-1b945.firebasestorage.app',
    measurementId: 'G-W6N1093BVH',
  );
}
